AWSTemplateFormatVersion: '2010-09-09'
Description: >
  'Creates a role that authorizes cross-account access from one aws account to a security audit role in another account.
  Grants access to the ViewOnlyAccess and SecurityAudit managed job functions in the target account. Deploy only in a single region.
  Last updated at 2024-03-18 23:46:12 by phillips.james@gmail.com'
Metadata:
  Version: 1.0
Parameters:
  Contact:
    Type: String
    Description: "contact resources for questions about this stack"
    Default: "James Phillips phillips.james@gmail.com"
  Owner:
    Type: String
    Description: "email address of owner of this stack"
  OrgPrefix:
    Type: String
    Description: "Organizational prefix for resources"
    Default: "opspath"
    AllowedPattern: "[a-z]*"
  PrincipalAccountId:
    Type: String
    Description: 12 digit id of the account containing the users to which you're granting access
    AllowedPattern: "\\d{12}"
Resources:
  AssumeRole:
    Type: AWS::IAM::Role
    Properties:
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonInspector2ReadOnlyAccess
        - arn:aws:iam::aws:policy/AWSSecurityHubReadOnlyAccess
        - arn:aws:iam::aws:policy/SecurityAudit
        - arn:aws:iam::aws:policy/job-function/ViewOnlyAccess
      RoleName: !Join [ "-", [ !Ref OrgPrefix, "CrossAccountSecurityAuditRole"] ]
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            AWS: "*" # this is done to allow the use of SSO in the PrincipalAccountId. 
            # By using the wildcard and the Condition key, you are trusting the PrincipalAccount to manage the user,
            # just the same as if you used AWS: !Sub 'arn:aws:iam::${PrincipalAccountId}:root' for an iam user.
          Action:
          - sts:AssumeRole
          Condition:
            StringEquals:
              aws:PrincipalAccount: !Ref PrincipalAccountId
      Policies:
           - PolicyName: AuditManagerReadOnlyAccess
             PolicyDocument: 
              Version: "2012-10-17"
              Statement:
              - Effect: Allow
                Action:
                - auditmanager:GetAccountStatus
                - auditmanager:GetAssessment
                - auditmanager:GetAssessmentFramework
                - auditmanager:GetAssessmentReportUrl
                - auditmanager:GetChangeLogs
                - auditmanager:GetControl
                - auditmanager:GetDelegations
                - auditmanager:GetEvidence
                - auditmanager:GetEvidenceByEvidenceFolder
                - auditmanager:GetEvidenceFileUploadUrl
                - auditmanager:GetEvidenceFolder
                - auditmanager:GetEvidenceFoldersByAssessment
                - auditmanager:GetEvidenceFoldersByAssessmentControl
                - auditmanager:GetInsights
                - auditmanager:GetInsightsByAssessment
                - auditmanager:GetOrganizationAdminAccount
                - auditmanager:GetServicesInScope
                - auditmanager:GetSettings
                - auditmanager:ListAssessmentControlInsightsByControlDomain
                - auditmanager:ListAssessmentFrameworkShareRequests
                - auditmanager:ListAssessmentFrameworks
                - auditmanager:ListAssessmentReports
                - auditmanager:ListAssessments
                - auditmanager:ListControlDomainInsights
                - auditmanager:ListControlDomainInsightsByAssessment
                - auditmanager:ListControlInsightsByControlDomain
                - auditmanager:ListControls
                - auditmanager:ListKeywordsForDataSource
                - auditmanager:ListNotifications
                - auditmanager:ListTagsForResource
                - auditmanager:ValidateAssessmentReportIntegrity
                Resource: !Sub "arn:${AWS::Partition}:auditmanager:${AWS::Region}:${AWS::AccountId}:*"
                Sid: AuditManagerAccess
              - Effect: Allow
                Action:
                - aws-portal:View*
                - notifications-contacts:GetEmailContact
                - notifications-contacts:ListEmailContacts
                - notifications-contacts:ListTagsForResource
                - notifications:GetEventRule
                - notifications:GetNotificationConfiguration
                - notifications:GetNotificationEvent
                - notifications:ListChannels
                - notifications:ListEventRules
                - notifications:ListNotificationConfigurations
                - notifications:ListNotificationEvents
                - notifications:ListNotificationHubs
                - notifications:ListTagsForResource
                Resource: "*"
                Sid: NotificationsReadOnly
      Tags:
        - Key: Owner
          Value: !Ref Owner
        - Key: Contact
          Value: !Ref Contact
Outputs:
  RootAdminRoleArn:
    Description: "CrossAccountSupportRole role Arn"
    Value: !GetAtt AssumeRole.Arn
  
